### ISSUE TITLE
Loosen version locking

### ISSUE THREAD

**Issue by carderne** [FrontierDevelopmentLab/sat-extractor#13]
I think it might be necessary to loosen the dependency version locking in `setup.py` a bit. Quite difficult to e.g. `pip install prefect[google] sat-extractor` because of the conflicts.

**Comment by carderne** [comment]
Something like this:
https://github.com/carderne/sat-extractor/commit/f192ab4a903b6babd9fead099f82afa77d26fc14

**Comment by carderne** [comment]
Also moved dash out of core requirements as not needed?

**Comment by frandorr** [comment]
Great, you are right. Feel free to create a PR! @carderne
