### ISSUE TITLE
mask and percentiles 

### ISSUE THREAD

**Issue by carderne** [FrontierDevelopmentLab/sat-extractor#18]
These don't seem to be used for anything?

https://github.com/FrontierDevelopmentLab/sat-extractor/blob/7a0821360ffdab8403563ca651b5bd43ecca3dc4/src/satextractor/preparer/preparer.py#L35-L51

**Comment by frandorr** [comment]
You are right. They are not being used at the moment. We should remove them and add a new feature to add these kind of things in a "plug-in" approach. Like, having the possibility to get custom info stored along the image arrays.
