### ISSUE TITLE
GCP dead-letter-queue not properly being created

### ISSUE THREAD

**Issue by frandorr** [FrontierDevelopmentLab/sat-extractor#6]
When the pubsub cloud run subscription is created, it creates also a dlq but it doesn't assign the correct roles and permissions and doesn't create the topic for the dlq:
![image](https://user-images.githubusercontent.com/1722574/139436218-5c2174ce-ca0c-42ea-8b20-e429952fe7c8.png)

As the dlq doesn't exist, the extraction task messages that fails will loop forever in the the main queue, restarting the cloud run service until messages are manually purged. 

We should add this permissions and create the dlq topic automatically to avoid an infinite loop.

**Comment by Lkruitwagen** [comment]
I think there was a typo in the dlq topic creation. Also I needed to use full account authorization in order to have permissions to assign the roles. Both covered in #7 !

**Comment by frandorr** [comment]
Great! Closing the issue then for now.
